#!/bin/bash

if [ ! -d "./configuration_files_from_secure_location" ]; then
    mkdir ./configuration_files_from_secure_location
fi

cd ./configuration_files_from_secure_location

openssl genrsa -out ./elency-config.private.pem 2048
openssl rsa -in ./elency-config.private.pem -outform PEM -pubout -out ./elency-config.public.pem

echo "{ \"mongoUrl\": \"mongodb://mongodb:27017/elency-config\", \"HMACAuthorizationKey\": \"NGM5YjYwZjhjZmQ4NGE5YWE1MmVhMTg3\", \"exposeUIRoutes\": true, \"maxJsonPostSize\": \"1mb\", \"sessionLifeTimeInMinutes\": 20160, \"validateAuthorizationTokenWindow\": true, \"authorizationTokenValidationWindowInSeconds\": 300 }" >> config.json
echo "{ \"configEncryptionKey\": \"MDdiNjYwNzFiYjk2NDgwMzliMTZkZmI1\" }" >> keys.json
cat ./config.json
CONFIG_FOLDER_PATH=./configuration_files_from_secure_location SEC_FOLDER_PATH=./configuration_files_from_secure_location node ../encrypt-configuration-files.js

node ../put-pem-key-on-one-line.js ./configuration_files_from_secure_location/elency-config.private.pem
node ../put-pem-key-on-one-line.js ./configuration_files_from_secure_location/elency-config.public.pem

CONFIG_JSON_VALUE=`cat ./config.json`
KEYS_JSON_VALUE=`cat ./keys.json`
PRIVATE_PEM_VALUE=`cat ./elency-config.private.pem`
PUBLIC_PEM_VALUE=`cat ./elency-config.public.pem`

rm ./config.json
rm ./keys.json
rm ./elency-config.private.pem
rm ./elency-config.public.pem

cd ..

CONFIG_JSON_VALUE=$CONFIG_JSON_VALUE KEYS_JSON_VALUE=$KEYS_JSON_VALUE PRIVATE_PEM_VALUE=$PRIVATE_PEM_VALUE PUBLIC_PEM_VALUE=$PUBLIC_PEM_VALUE docker-compose up