#!/bin/bash

package='v8-profiler'
if [ `npm list -g | grep -c $package` -eq 0 ]; then
    npm install $package -g --no-shrinkwrap
fi

package='pm2'
if [ `npm list -g | grep -c $package` -eq 0 ]; then
    npm install $package -g --no-shrinkwrap
fi

pm2 startup systemd
pm2 start index.js -i 1 --name elency-config-server

